import type { Metadata } from "next";
import "./globals.css";
import AuthButton from "@/components/AuthButton"
import SessionProviderWrapper from "./SessionProviderWrapper"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <SessionProviderWrapper>
          <AuthButton />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
